name: JavaFX JLink Build and Release

#on:
#  push:
#    branches:
#      - main
#      - master
#  release:
#    types: [created]

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          java-package: 'jdk'
          cache: 'maven'

      - name: Build with Maven (JLink)
        run: mvn clean javafx:jlink

      - name: Create Release Artifact
        run: |
          mkdir -p release
          mv target/app.zip release/app-${{ matrix.os }}.zip

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ matrix.os }}
          path: release/app-${{ matrix.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract tag name
        id: tag
        run: echo "TAG_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          files: |
            release/*.zip
