name: JavaFX JLink Build and Release

on:
  push:
    branches:
      - main
      - master
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          java-package: 'jdk'
          cache: 'maven'

      - name: Build with Maven (JLink)
        run: mvn clean javafx:jlink

      - name: Determine Platform
        id: platform
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "Platform=Ubuntu" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "Darwin" ]]; then
            echo "Platform=Mac" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "Platform=Windows" >> $GITHUB_ENV
          fi

      - name: Create Release Artifact
        run: |
          mkdir -p release
          mv target/app.zip release/app-${{ env.Platform }}.zip

      - name: Check if Tag Exists
        id: check_tag
        run: |
          TAG_NAME="v1.0.${{ github.run_number }}"
          echo "Checking if tag $TAG_NAME already exists..."
          if git tag -l | grep -q "^$TAG_NAME$"; then
            echo "Tag $TAG_NAME already exists. Skipping tag creation."
          else
            echo "Tag $TAG_NAME does not exist. Creating new tag."
            git tag $TAG_NAME
            git push origin $TAG_NAME
          fi
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Upload Release Artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/app-${{ env.Platform }}.zip
          tag: v1.0.${{ env.TAG_NAME }}